### ISSUE TITLE
onBeforeUnload being called but not stopping browser from navigating away

### ISSUE THREAD

**Issue by tnrich** [szymonkaliski/react-window-mixins#2]
Hey there, I'm having an issue with the onBeforeUnload functionality. When I run the following code using webpack's dev server, the console logs "onBeforeUnload hit!" when I navigate away from the page, but it doesn't actually prompt me to confirm leaving. 

Any chance you know why that might be? Is it something to do with webpack perhaps, or have other people also experienced this issue not using webpack?

Here's a simplified version of the code I'm running:

``` javascript
var React = require('react');
var OnUnload = require("react-window-mixins").OnUnload;


var App = React.createClass({
  mixins: [OnUnload],

  onBeforeUnload: function() {
    console.log('onBeforeUnload hit!');
    return 'Are you sure you want to leave the page?';
  },


    return (
      <div overflow='scroll'>

      </div>
    );
  }
});

React.render(<App tree={baobabTree}/>, document.body);

```

Thanks!
Thomas

**Comment by szymonkaliski** [comment]
I think it would be best if @jeffkole answered this as he added this functionality. 
There's a chance that this is a browser-related problem → http://stackoverflow.com/questions/7389554/crossbrowser-onbeforeunload

**Comment by jeffkole** [comment]
Sorry that I don't have a better answer for you, but I agree that it is likely a browser issue.  I have found browsers' implementations of `beforeupload` to be rather flaky, and while we use it, we do not absolutely rely on it.  I would rule out webpack as the issue though.

You might try debugging by attaching the `onBeforeUnload` function directly to the window instead of using the mixin and seeing what happens.  Something like:

``` javascript
var React = require('react');

window.addEventListener('beforeunload', function() {
  console.log('onBeforeUnload hit!');
  return 'Are you sure you want to leave the page?';
});

var App = React.createClass({
  render: function () {
    return (
      <div overflow='scroll'>

      </div>
    );
  }
});

React.render(<App tree={baobabTree}/>, document.body);
```

(And, totally unrelated, the general practice is to attach a React app to a `<div>` inside the body instead of directly to the body.  Since many libraries often rely on adding scripts dynamically to the body directly, they can cause conflict with React, which expects the elements of the DOM that it handles not to be changed by anyone else.)

**Comment by tnrich** [comment]
Hey @jeffkole, thanks for the helpful reply.

It appears it is something to do with the browser implementation, not your mixin. I wonder why that would be... I'm on the most recent version of chrome where you'd think this functionality would be working. 

When you say you don't absolutely rely on it, what other solutions do you have in place?

**Comment by jeffkole** [comment]
We use it to signal back to our servers that a user has left a specific page in an attempt to clean up some of the resources related to that page (we display some presence data).  We also have an expiration and heartbeating mechanism in place to clean up the data as well, since the `onbeforeunload` event is so unreliable.

**Comment by buhe** [comment]
``` javascript
window.addEventListener("beforeunload", function (e) {
    var confirmationMessage = 'It looks like you have been editing something.';
    confirmationMessage += 'If you leave before saving, your changes will be lost.';

    (e || window.event).returnValue = confirmationMessage; //Gecko + IE
    return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
});
```

or

``` javascript
mixins: [ OnUnload ],

    onUnload: function() {
        // Clean up any resources
    },

    onBeforeUnload: function(e) {
        var confirmationMessage = 'It looks like you have been editing something.';

        (e || window.event).returnValue = confirmationMessage; //Gecko + IE, Chrome(mac os)
        return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
    },
```

(e || window.event).returnValue = confirmationMessage;  
this line save my life on chrome(mac os).

**Comment by tnrich** [comment]
awesome, thanks buhe! That fixed the issue I was seeing.

**Comment by tnrich** [comment]
Seems like it is just an osx thing.
